IF DB_ID('LibraryDb') IS NULL CREATE DATABASE LibraryDb; GO
USE LibraryDb; GO
IF OBJECT_ID('Authors','U') IS NULL CREATE TABLE Authors (Id INT IDENTITY(1,1) PRIMARY KEY, FirstName NVARCHAR(100) NOT NULL, LastName NVARCHAR(100) NOT NULL, Bio NVARCHAR(MAX) NULL, BirthDate DATE NULL, CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()); GO
IF OBJECT_ID('Categories','U') IS NULL CREATE TABLE Categories (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(100) NOT NULL UNIQUE, Description NVARCHAR(255), CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()); GO
IF OBJECT_ID('Publishers','U') IS NULL CREATE TABLE Publishers (Id INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(150) NOT NULL UNIQUE, Address NVARCHAR(255) NULL, City NVARCHAR(100) NULL, Country NVARCHAR(100) NULL, CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()); GO
IF OBJECT_ID('Books','U') IS NULL CREATE TABLE Books (Id INT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(255) NOT NULL, ISBN NVARCHAR(20) NOT NULL UNIQUE, PublicationYear INT NULL, CategoryId INT NOT NULL, PublisherId INT NULL, Description NVARCHAR(MAX) NULL, PageCount INT NULL, Language NVARCHAR(50) DEFAULT 'English', CopiesAvailable INT DEFAULT 0, CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_Books_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id), CONSTRAINT FK_Books_Publishers FOREIGN KEY (PublisherId) REFERENCES Publishers(Id)); GO
IF OBJECT_ID('BookAuthors','U') IS NULL CREATE TABLE BookAuthors (BookId INT NOT NULL, AuthorId INT NOT NULL, CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(), PRIMARY KEY (BookId, AuthorId), CONSTRAINT FK_BookAuthors_Books FOREIGN KEY (BookId) REFERENCES Books(Id) ON DELETE CASCADE, CONSTRAINT FK_BookAuthors_Authors FOREIGN KEY (AuthorId) REFERENCES Authors(Id) ON DELETE CASCADE); GO
IF OBJECT_ID('Members','U') IS NULL CREATE TABLE Members (Id INT IDENTITY(1,1) PRIMARY KEY, FirstName NVARCHAR(100) NOT NULL, LastName NVARCHAR(100) NOT NULL, Email NVARCHAR(150) NOT NULL UNIQUE, Phone NVARCHAR(50) NULL, Address NVARCHAR(255) NULL, City NVARCHAR(100) NULL, State NVARCHAR(100) NULL, PostalCode NVARCHAR(20) NULL, MembershipDate DATETIME2 DEFAULT SYSUTCDATETIME(), IsActive BIT DEFAULT 1); GO
IF OBJECT_ID('Loans','U') IS NULL CREATE TABLE Loans (Id INT IDENTITY(1,1) PRIMARY KEY, BookId INT NOT NULL, MemberId INT NOT NULL, LoanDate DATETIME2 DEFAULT SYSUTCDATETIME(), DueDate DATETIME2 NOT NULL, ReturnDate DATETIME2 NULL, Status NVARCHAR(50) DEFAULT 'Borrowed', CONSTRAINT FK_Loans_Books FOREIGN KEY (BookId) REFERENCES Books(Id), CONSTRAINT FK_Loans_Members FOREIGN KEY (MemberId) REFERENCES Members(Id)); GO
IF OBJECT_ID('Reservations','U') IS NULL CREATE TABLE Reservations (Id INT IDENTITY(1,1) PRIMARY KEY, BookId INT NOT NULL, MemberId INT NOT NULL, ReservationDate DATETIME2 DEFAULT SYSUTCDATETIME(), Status NVARCHAR(50) DEFAULT 'Active', CONSTRAINT FK_Reservations_Books FOREIGN KEY (BookId) REFERENCES Books(Id), CONSTRAINT FK_Reservations_Members FOREIGN KEY (MemberId) REFERENCES Members(Id)); GO
IF OBJECT_ID('Fines','U') IS NULL CREATE TABLE Fines (Id INT IDENTITY(1,1) PRIMARY KEY, LoanId INT NOT NULL, Amount DECIMAL(10,2) NOT NULL, Paid BIT DEFAULT 0, IssuedDate DATETIME2 DEFAULT SYSUTCDATETIME(), PaidDate DATETIME2 NULL, CONSTRAINT FK_Fines_Loans FOREIGN KEY (LoanId) REFERENCES Loans(Id) ON DELETE CASCADE); GO
IF NOT EXISTS (SELECT 1 FROM Categories) INSERT INTO Categories (Name, Description) VALUES ('Fiction','Literary works created from imagination'), ('Non-Fiction','Informative and factual books'), ('Science Fiction','Futuristic and science-based stories'), ('Fantasy','Magical and mythical tales'), ('Mystery','Crime and detective stories'), ('Biography','Life stories of individuals'), ('History','Books about historical events'), ('Self-Help','Guides for personal improvement'), ('Romance','Love and relationship stories'), ('Horror','Scary and suspenseful tales'); GO
IF NOT EXISTS (SELECT 1 FROM Publishers) INSERT INTO Publishers (Name, Address, City, Country) VALUES ('Penguin Random House','1745 Broadway','New York','USA'), ('HarperCollins','195 Broadway','New York','USA'), ('Simon & Schuster','1230 Avenue of the Americas','New York','USA'), ('Hachette Book Group','1290 Avenue of the Americas','New York','USA'), ('Macmillan Publishers','120 Broadway','New York','USA'); GO
IF NOT EXISTS (SELECT 1 FROM Authors) INSERT INTO Authors (FirstName, LastName, Bio, BirthDate) VALUES ('George','Orwell','English novelist and essayist, known for dystopian works.','1903-06-25'), ('J.K.','Rowling','British author, best known for the Harry Potter series.','1965-07-31'), ('Isaac','Asimov','Prolific science fiction writer and professor of biochemistry.','1920-01-02'), ('Agatha','Christie','Famous mystery writer, known as the Queen of Crime.','1890-09-15'), ('Stephen','King','American author of horror, supernatural fiction, and suspense.','1947-09-21'), ('Jane','Austen','English novelist known for romantic fiction.','1775-12-16'), ('Walter','Isaacson','Biographer known for works on Steve Jobs and Leonardo da Vinci.','1952-05-20'), ('Yuval Noah','Harari','Historian and author of Sapiens.','1976-02-24'), ('Dale','Carnegie','Author of self-help classics.','1888-11-24'), ('J.R.R.','Tolkien','Author of high fantasy works like The Lord of the Rings.','1892-01-03'); GO
IF NOT EXISTS (SELECT 1 FROM Books) INSERT INTO Books (Title, ISBN, PublicationYear, CategoryId, PublisherId, Description, PageCount, Language, CopiesAvailable) VALUES ('1984','9780451524935',1949,3,1,'A dystopian novel about a totalitarian regime.',328,'English',5), ('Harry Potter and the Sorcerer''s Stone','9780590353427',1997,4,2,'A young wizard begins his magical journey.',309,'English',10), ('Foundation','9780553293357',1951,3,1,'A science fiction saga about the fall of a galactic empire.',255,'English',6), ('Murder on the Orient Express','9780062693662',1934,5,2,'Detective Hercule Poirot investigates a murder on a train.',256,'English',4), ('The Shining','9780307743657',1977,10,3,'A family heads to an isolated hotel with sinister forces.',447,'English',3), ('Pride and Prejudice','9780141439518',1813,9,4,'A classic romance exploring manners and marriage.',279,'English',7), ('Steve Jobs','9781451648539',2011,6,5,'Biography of Apple co-founder Steve Jobs.',656,'English',5), ('Sapiens: A Brief History of Humankind','9780062316097',2011,7,2,'Exploration of human history and evolution.',498,'English',8), ('How to Win Friends and Influence People','9780671027032',1936,8,3,'Timeless principles for effective communication.',291,'English',9), ('The Hobbit','9780547928227',1937,4,5,'A fantasy adventure preceding The Lord of the Rings.',310,'English',6); GO
IF NOT EXISTS (SELECT 1 FROM BookAuthors) INSERT INTO BookAuthors (BookId, AuthorId) VALUES (1,1), (2,2), (3,3), (4,4), (5,5), (6,6), (7,7), (8,8), (9,9), (10,10); GO
IF NOT EXISTS (SELECT 1 FROM Members) INSERT INTO Members (FirstName, LastName, Email, Phone, Address, City, State, PostalCode) VALUES ('John','Doe','john.doe@example.com','555-1234','123 Main St','Oklahoma City','OK','73101'), ('Jane','Smith','jane.smith@example.com','555-5678','456 Elm St','Oklahoma City','OK','73102'), ('Michael','Johnson','michael.johnson@example.com','555-8765','789 Oak St','Oklahoma City','OK','73103'), ('Emily','Davis','emily.davis@example.com','555-4321','321 Pine St','Oklahoma City','OK','73104'), ('William','Brown','william.brown@example.com','555-2468','654 Maple St','Oklahoma City','OK','73105'); GO
IF NOT EXISTS (SELECT 1 FROM Loans) INSERT INTO Loans (BookId, MemberId, DueDate, Status) VALUES (1,1,DATEADD(DAY,14,SYSUTCDATETIME()),'Borrowed'), (2,2,DATEADD(DAY,14,SYSUTCDATETIME()),'Borrowed'), (3,3,DATEADD(DAY,14,SYSUTCDATETIME()),'Borrowed'), (4,4,DATEADD(DAY,14,SYSUTCDATETIME()),'Borrowed'), (5,5,DATEADD(DAY,14,SYSUTCDATETIME()),'Borrowed'); GO
IF NOT EXISTS (SELECT 1 FROM Reservations) INSERT INTO Reservations (BookId, MemberId) VALUES (6,1), (7,2), (8,3), (9,4), (10,5); GO
IF NOT EXISTS (SELECT 1 FROM Fines) INSERT INTO Fines (LoanId, Amount, Paid) VALUES (1,2.50,0), (2,1.75,1), (3,3.00,0); GO